// FrankyCPP
// Copyright (c) 2018-2026 Frank Kopp
//
// MIT License
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#include "tuning/optimizer/TuningOutput.h"

#include "common/Logging.h"
#include "tuning/optimizer/TuningState.h"
#include "types/globals.h"

#include <algorithm>
#include <cstdlib>
#include <format>
#include <fstream>
#include <iostream>
#include <map>
#include <ranges>
#include <sstream>
#include <stdexcept>
#include <vector>

namespace tuning {

  // =========================================================================
  // YAML generation
  // =========================================================================

  std::string TuningOutput::generateParamsYaml(
    const std::vector<TuningParameter>& params,
    const double K) {

    std::ostringstream out;

    // Header
    out << "# FrankyCPP Tuned Evaluation Parameters\n";
    out << "# Generated by Texel Tuner\n";
    out << "# Timestamp: " << TuningState::currentTimestamp() << "\n";
    if (K > 0.0) {
      out << std::format("# Scaling constant K: {:.6f}\n", K);
    }
    out << "#\n";
    out << "# Copy this file to config/eval.yaml to use these parameters.\n";
    out << "# Or load via: FrankyCPP --eval-config tuned_params.yaml\n";
    out << "\n";

    // Coalesce array elements back into single entries.
    // We process params in order and group consecutive array elements
    // with the same configName into a single comma-separated line.
    //
    // Use an ordered map to collect: configName → value string.
    // For scalars: "42"
    // For arrays: "0,5,15,35,70,120"
    struct ParamEntry {
      std::string configName;
      std::string valueStr;
      int order{};  // preserve original ordering
    };

    std::map<std::string, ParamEntry> entries;
    int orderCounter = 0;

    for (const auto& p : params) {
      if (p.arrayIndex >= 0) {
        // Array element — accumulate into the array's entry
        auto it = entries.find(p.configName);
        if (it == entries.end()) {
          // First element of this array — create with placeholder slots
          ParamEntry entry;
          entry.configName = p.configName;
          entry.order = orderCounter++;
          // Build array with proper size
          std::vector<int> arr(p.arraySize, 0);
          arr[p.arrayIndex] = p.currentValue;
          // Store as comma-separated (will be rebuilt when all elements are collected)
          // Actually, store a vector of ints as a temporary — but we only have strings.
          // Instead, store elements in a side structure.
          entries[p.configName] = entry;

          // We'll rebuild the value string after collecting all elements.
          // For now, just mark it.
          entries[p.configName].valueStr = "";
        }
      }
      else {
        // Scalar parameter
        ParamEntry entry;
        entry.configName = p.configName;
        entry.valueStr   = std::to_string(p.currentValue);
        entry.order      = orderCounter++;
        entries[p.configName] = entry;
      }
    }

    // Second pass: build array value strings from the actual param elements
    // Group array elements by configName and sort by arrayIndex
    std::map<std::string, std::vector<std::pair<int, int>>> arrayElements; // configName → [(index, value)]
    for (const auto& p : params) {
      if (p.arrayIndex >= 0) {
        arrayElements[p.configName].emplace_back(p.arrayIndex, p.currentValue);
      }
    }
    for (auto& [configName, elements] : arrayElements) {
      std::ranges::sort(elements);
      std::ostringstream arrStr;
      for (std::size_t i = 0; i < elements.size(); ++i) {
        if (i > 0) arrStr << ",";
        arrStr << elements[i].second;
      }
      if (entries.contains(configName)) {
        entries[configName].valueStr = arrStr.str();
      }
    }

    // Sort entries by their original order
    std::vector<const ParamEntry*> sorted;
    sorted.reserve(entries.size());
    for (const auto& entry : entries | std::views::values) {
      sorted.push_back(&entry);
    }
    std::ranges::sort(sorted,
              [](const ParamEntry* a, const ParamEntry* b) { return a->order < b->order; });

    // Write entries
    for (const auto* entry : sorted) {
      out << entry->configName << ": " << entry->valueStr << "\n";
    }

    return out.str();
  }

  void TuningOutput::writeParamsYaml(const std::string& path,
                                     const std::vector<TuningParameter>& params,
                                     const double K) {
    const auto content = generateParamsYaml(params, K);

    std::ofstream file(path);
    if (!file.is_open()) {
      throw std::runtime_error(std::format("TuningOutput::writeParamsYaml: cannot open file for writing: {}", path));
    }
    file << content;
    file.close();

    LOG__INFO(common::Logger::get().TUNING_LOG, "Tuned parameters written to: {}", path);
  }

  // =========================================================================
  // Comparison report generation
  // =========================================================================

  std::string TuningOutput::generateComparisonReport(const std::vector<TuningParameter>& params) {
    std::ostringstream out;

    // Header
    out << "FrankyCPP Texel Tuning -- Parameter Comparison Report\n";
    out << "Generated: " << TuningState::currentTimestamp() << "\n";
    out << std::string(80, '=') << "\n\n";

    // Statistics
    int totalParams   = 0;
    int changedCount  = 0;
    int unchangedCount = 0;
    int signFlipped   = 0;
    int zeroedOut     = 0;

    for (const auto& p : params) {
      ++totalParams;
      if (p.currentValue != p.originalValue) {
        ++changedCount;
        // Sign flip: original and current have opposite signs (both non-zero)
        if (p.originalValue != 0 && p.currentValue != 0 &&
            ((p.originalValue > 0) != (p.currentValue > 0))) {
          ++signFlipped;
        }
        // Zeroed out: was non-zero, now zero
        if (p.originalValue != 0 && p.currentValue == 0) {
          ++zeroedOut;
        }
      }
      else {
        ++unchangedCount;
      }
    }

    out << std::format("Total parameters:  {}\n", totalParams);
    out << std::format("Changed:           {} ({:.1f}%)\n",
                       changedCount, 100.0 * changedCount / std::max(totalParams, 1));
    out << std::format("Unchanged:         {}\n", unchangedCount);
    if (signFlipped > 0) {
      out << std::format("Sign-flipped:      {} (WARNING)\n", signFlipped);
    }
    if (zeroedOut > 0) {
      out << std::format("Zeroed out:        {} (candidates for removal)\n", zeroedOut);
    }
    out << "\n";

    // Table header
    const auto header = std::format("{:<45s} {:>8s} {:>8s} {:>8s} {:>8s}  {}\n",
                                    "Parameter", "Original", "Tuned", "Delta", "Change%", "Flags");
    out << header;
    out << std::string(header.size() - 1, '-') << "\n";

    // Table rows — sorted by configName for readability (arrays grouped together)
    for (const auto& p : params) {
      const int delta = p.currentValue - p.originalValue;

      // Calculate change percentage (relative to original, guarded against div-by-zero)
      std::string changeStr;
      if (p.originalValue != 0) {
        const double changePct = 100.0 * static_cast<double>(delta) / static_cast<double>(std::abs(p.originalValue));
        changeStr = std::format("{:>+7.1f}%", changePct);
      }
      else if (delta != 0) {
        changeStr = "    new";
      }
      else {
        changeStr = "       ";
      }

      // Flags
      std::string flags;
      if (p.originalValue != 0 && p.currentValue != 0 &&
          ((p.originalValue > 0) != (p.currentValue > 0))) {
        flags += " SIGN-FLIP";
      }
      if (p.originalValue != 0 && p.currentValue == 0) {
        flags += " ->ZERO";
      }
      if (delta == 0) {
        flags += " (unchanged)";
      }

      out << std::format("{:<45s} {:>8d} {:>8d} {:>+8d} {:>8s}  {}\n",
                         p.name, p.originalValue, p.currentValue, delta, changeStr, flags);
    }

    return out.str();
  }

  void TuningOutput::writeComparisonReport(const std::string& path,
                                           const std::vector<TuningParameter>& params) {
    const auto content = generateComparisonReport(params);

    std::ofstream file(path);
    if (!file.is_open()) {
      throw std::runtime_error(
        std::format("TuningOutput::writeComparisonReport: cannot open file for writing: {}", path));
    }
    file << content;
    file.close();

    LOG__INFO(common::Logger::get().TUNING_LOG, "Comparison report written to: {}", path);
  }

  // =========================================================================
  // Console summary
  // =========================================================================

  void TuningOutput::printComparisonSummary(const std::vector<TuningParameter>& params,
                                            const int topN) {
    // Count statistics
    int changedCount  = 0;
    int signFlipped   = 0;
    int zeroedOut     = 0;

    for (const auto& p : params) {
      if (p.currentValue != p.originalValue) {
        ++changedCount;
        if (p.originalValue != 0 && p.currentValue != 0 &&
            ((p.originalValue > 0) != (p.currentValue > 0))) {
          ++signFlipped;
        }
        if (p.originalValue != 0 && p.currentValue == 0) {
          ++zeroedOut;
        }
      }
    }

    std::cout << "\nParameter Summary:\n";
    std::cout << std::format("  Changed:       {}/{}\n", changedCount, params.size());
    if (signFlipped > 0) {
      std::cout << std::format("  Sign-flipped:  {} (WARNING - review these!)\n", signFlipped);
    }
    if (zeroedOut > 0) {
      std::cout << std::format("  Zeroed out:    {} (candidates for removal)\n", zeroedOut);
    }

    // Top movers
    std::vector<const TuningParameter*> movers;
    movers.reserve(params.size());
    for (const auto& p : params) {
      if (p.currentValue != p.originalValue) {
        movers.push_back(&p);
      }
    }
    std::ranges::sort(movers,
              [](const TuningParameter* a, const TuningParameter* b) {
                return std::abs(a->currentValue - a->originalValue) >
                       std::abs(b->currentValue - b->originalValue);
              });

    const int showCount = std::min(topN, static_cast<int>(movers.size()));
    if (showCount > 0) {
      std::cout << "\n  Top " << showCount << " parameter changes:\n";
      std::cout << std::format("  {:<45s} {:>8s} {:>8s} {:>8s}\n",
                               "Parameter", "Original", "Tuned", "Delta");
      std::cout << "  " << std::string(69, '-') << "\n";
      for (int i = 0; i < showCount; ++i) {
        const auto* p = movers[i];
        const int delta = p->currentValue - p->originalValue;
        std::cout << std::format("  {:<45s} {:>8d} {:>8d} {:>+8d}\n",
                                 p->name, p->originalValue, p->currentValue, delta);
      }
    }
    std::cout << "\n";
  }

} // namespace tuning
