dist: trusty
sudo: required
language: cpp
compiler: gcc
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9

env:env: COMPILER=g++ C_COMPILER=gcc BUILD_TYPE=Release

before_script:
  - source .travis-pre-setup.sh;
  - mkdir -p build && cd build

script:
  # Check versions of gcc, g++ and cmake
  - which gcc && which g++ && which cmake
  - gcc -v && g++ -v && cmake --version
  # Update to gcc-9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
  - sudo update-alternatives --set gcc /usr/bin/gcc-9
  - sudo update-alternatives --set g++ /usr/bin/g++-9
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  # Check versions of gcc, g++ and cmake
  - which gcc && which g++ && which cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

#install:
#  travis_wait sudo -E apt-get -yq --no-install-suggests --no-install-recommends install gcc-10;

