sudo: required
language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
env: COMPILER=g++ C_COMPILER=gcc BUILD_TYPE=Release

before_script:
  source .travis-pre-setup.sh;
  

