language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake

before_install:
  - sudo apt purge cmake
  - wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4.tar.gz
  - tar -zxcf cmake-3.13.4.tar.gz
  - cd cmake-3.13.4
  - sudo ./bootstrap
  - sudo make
  - sudo make install
  - cmake --version

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cmake CMakeLists.txt
  - cmake  --build . 

