branches:
  only:
    - master
    - develop
    - /dev_.*$/

dist: xenial
sudo: required
language: cpp
compiler: gcc
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9

env: COMPILER=g++ C_COMPILER=gcc BUILD_TYPE=Release

before_install:
  # Check versions of gcc, g++ and cmake
  - which gcc && which g++ && which cmake
  - gcc -v && g++ -v && cmake --version

install:
  # Update to gcc-9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
  - sudo update-alternatives --set gcc /usr/bin/gcc-9
  - sudo update-alternatives --set g++ /usr/bin/g++-9
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  # Newer CMAKE
  - curl -sSL https://cmake.org/files/v3.18/cmake-3.18.2-Linux-x86_64.sh -o install-cmake.sh
  - chmod +x install-cmake.sh
  - sudo ./install-cmake.sh --prefix=/usr/local --skip-license
  - export PATH=/usr/local/bin:$PATH;
  # BOOST
  - wget https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.gz >> /dev/null 2>&1
  - tar xfz boost_1_73_0.tar.gz
  - cd boost_1_73_0/
  - ./bootstrap.sh --with-libraries=serialization,program_options >> /dev/null 2>&1
  - ./b2 >> /dev/null 2>&1
  - sudo ./b2 install  >> /dev/null 2>&1
  - cd ..

before_script:
  # Check versions of gcc, g++ and cmake
  - which gcc && which g++ && which cmake
  - gcc -v && g++ -v && cmake --version
  - mkdir -p build && cd build

script:
  # Run your build commands next
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DBENCHMARK_ENABLE_TESTING=OFF -DBENCHMARK_ENABLE_LTO=true ..
  - make -j
  - ls -l ./src
  - ls -l ./test
  - ls -l ./testbench
  - ctest -C ${BUILD_TYPE} -DBENCHMARK_ENABLE_TESTING=OFF -E ".*SpeedTests.*" -E ".*TimingTests.*" --output-on-failure
  - ./testbench/FrankyCPP_v0.3_Bench


