sudo: required
language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
env: COMPILER=g++-10 C_COMPILER=gcc-10 BUILD_TYPE=Release

before_script:
  source .travis-pre-setup.sh;

install:
  travis_wait sudo -E apt-get -yq --no-install-suggests --no-install-recommends install gcc-10;

