// FrankyCPP
// Copyright (c) 2018-2026 Frank Kopp
//
// MIT License
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#include "tuning/optimizer/TuningOutput.h"

#include "config/ConfigManager.h"
#include "init.h"
#include "tuning/optimizer/TuningParameter.h"
#include "types/macros.h"

#include <filesystem>
#include <fstream>
#include <gtest/gtest.h>
#include <string>

using namespace tuning;
using namespace config;

class TuningOutputTest : public testing::Test {
public:
  static void SetUpTestSuite() {
    NEWLINE;
    init::init();
    NEWLINE;
  }

protected:
  /// Helper: create a small param vector for testing
  static std::vector<TuningParameter> makeTestParams() {
    std::vector<TuningParameter> params;

    // Scalar param — changed
    TuningParameter p1;
    p1.name          = "TEMPO";
    p1.configName    = "TEMPO";
    p1.originalValue = 34;
    p1.currentValue  = 30;
    p1.arrayIndex    = -1;
    p1.arraySize     = 0;
    params.push_back(p1);

    // Scalar param — unchanged
    TuningParameter p2;
    p2.name          = "ISOLATED_PAWN_MID_WEIGHT";
    p2.configName    = "ISOLATED_PAWN_MID_WEIGHT";
    p2.originalValue = -10;
    p2.currentValue  = -10;
    p2.arrayIndex    = -1;
    p2.arraySize     = 0;
    params.push_back(p2);

    // Scalar param — sign flip
    TuningParameter p3;
    p3.name          = "BLOCKED_PAWN_MID_WEIGHT";
    p3.configName    = "BLOCKED_PAWN_MID_WEIGHT";
    p3.originalValue = -2;
    p3.currentValue  = 1;
    p3.arrayIndex    = -1;
    p3.arraySize     = 0;
    params.push_back(p3);

    // Scalar param — zeroed out
    TuningParameter p4;
    p4.name          = "SPACE_BONUS_END";
    p4.configName    = "SPACE_BONUS_END";
    p4.originalValue = 1;
    p4.currentValue  = 0;
    p4.arrayIndex    = -1;
    p4.arraySize     = 0;
    params.push_back(p4);

    // Array param — 3 elements
    for (int i = 0; i < 3; ++i) {
      TuningParameter pa;
      pa.name          = "TEST_ARRAY[" + std::to_string(i) + "]";
      pa.configName    = "TEST_ARRAY";
      pa.originalValue = i * 10;       // 0, 10, 20
      pa.currentValue  = i * 10 + 5;   // 5, 15, 25
      pa.arrayIndex    = i;
      pa.arraySize     = 3;
      params.push_back(pa);
    }

    return params;
  }

  /// Helper: read a file into a string
  static std::string readFile(const std::string& path) {
    std::ifstream ifs(path);
    return {std::istreambuf_iterator<char>(ifs), std::istreambuf_iterator<char>()};
  }
};

// =========================================================================
// YAML generation tests
// =========================================================================

TEST_F(TuningOutputTest, GenerateParamsYaml_ContainsHeader) {
  const auto params = makeTestParams();
  const auto yaml = TuningOutput::generateParamsYaml(params, 1.196);

  EXPECT_TRUE(yaml.find("FrankyCPP Tuned Evaluation Parameters") != std::string::npos);
  EXPECT_TRUE(yaml.find("Generated by Texel Tuner") != std::string::npos);
  EXPECT_TRUE(yaml.find("1.196") != std::string::npos) << "K value should be in header";
}

TEST_F(TuningOutputTest, GenerateParamsYaml_ScalarParams) {
  const auto params = makeTestParams();
  const auto yaml = TuningOutput::generateParamsYaml(params);

  // Scalar params should appear as "KEY: value"
  EXPECT_TRUE(yaml.find("TEMPO: 30") != std::string::npos);
  EXPECT_TRUE(yaml.find("ISOLATED_PAWN_MID_WEIGHT: -10") != std::string::npos);
  EXPECT_TRUE(yaml.find("BLOCKED_PAWN_MID_WEIGHT: 1") != std::string::npos);
  EXPECT_TRUE(yaml.find("SPACE_BONUS_END: 0") != std::string::npos);
}

TEST_F(TuningOutputTest, GenerateParamsYaml_ArrayCoalesced) {
  const auto params = makeTestParams();
  const auto yaml = TuningOutput::generateParamsYaml(params);

  // Array elements should be coalesced into single comma-separated line
  EXPECT_TRUE(yaml.find("TEST_ARRAY: 5,15,25") != std::string::npos)
    << "Array should be coalesced. YAML:\n" << yaml;

  // Individual array element names should NOT appear
  EXPECT_TRUE(yaml.find("TEST_ARRAY[0]") == std::string::npos);
  EXPECT_TRUE(yaml.find("TEST_ARRAY[1]") == std::string::npos);
}

TEST_F(TuningOutputTest, GenerateParamsYaml_EmptyParams) {
  // ReSharper disable once CppVariableCanBeMadeConstexpr
  const std::vector<TuningParameter> empty;
  const auto yaml = TuningOutput::generateParamsYaml(empty);

  // Should still have header but no param lines
  EXPECT_TRUE(yaml.find("FrankyCPP Tuned Evaluation Parameters") != std::string::npos);
  EXPECT_TRUE(yaml.find("TEMPO") == std::string::npos);
}

TEST_F(TuningOutputTest, WriteParamsYaml_CreatesFile) {
  const auto params = makeTestParams();
  const std::string path = "test_tuning_output.yaml";

  TuningOutput::writeParamsYaml(path, params, 1.2);
  ASSERT_TRUE(std::filesystem::exists(path));

  const auto content = readFile(path);
  EXPECT_TRUE(content.find("TEMPO: 30") != std::string::npos);
  EXPECT_TRUE(content.find("TEST_ARRAY: 5,15,25") != std::string::npos);

  std::filesystem::remove(path);
}

TEST_F(TuningOutputTest, WriteParamsYaml_BadPath) {
  const auto params = makeTestParams();
  EXPECT_THROW(TuningOutput::writeParamsYaml("/nonexistent/dir/file.yaml", params), std::runtime_error);
}

// =========================================================================
// Comparison report tests
// =========================================================================

TEST_F(TuningOutputTest, GenerateComparisonReport_ContainsHeader) {
  const auto params = makeTestParams();
  const auto report = TuningOutput::generateComparisonReport(params);

  EXPECT_TRUE(report.find("Parameter Comparison Report") != std::string::npos);
  EXPECT_TRUE(report.find("Total parameters:") != std::string::npos);
}

TEST_F(TuningOutputTest, GenerateComparisonReport_CorrectStatistics) {
  const auto params = makeTestParams();
  const auto report = TuningOutput::generateComparisonReport(params);

  // 7 total params (4 scalar + 3 array)
  EXPECT_TRUE(report.find("Total parameters:  7") != std::string::npos);
  // 1 unchanged (ISOLATED_PAWN_MID_WEIGHT)
  EXPECT_TRUE(report.find("Unchanged:         1") != std::string::npos);
  // 1 sign flip (BLOCKED_PAWN_MID_WEIGHT: -2 -> 1)
  EXPECT_TRUE(report.find("Sign-flipped:      1") != std::string::npos);
  // 1 zeroed out (SPACE_BONUS_END: 1 -> 0)
  EXPECT_TRUE(report.find("Zeroed out:        1") != std::string::npos);
}

TEST_F(TuningOutputTest, GenerateComparisonReport_ContainsAllParams) {
  const auto params = makeTestParams();
  const auto report = TuningOutput::generateComparisonReport(params);

  EXPECT_TRUE(report.find("TEMPO") != std::string::npos);
  EXPECT_TRUE(report.find("ISOLATED_PAWN_MID_WEIGHT") != std::string::npos);
  EXPECT_TRUE(report.find("BLOCKED_PAWN_MID_WEIGHT") != std::string::npos);
  EXPECT_TRUE(report.find("SPACE_BONUS_END") != std::string::npos);
  EXPECT_TRUE(report.find("TEST_ARRAY[0]") != std::string::npos);
  EXPECT_TRUE(report.find("TEST_ARRAY[2]") != std::string::npos);
}

TEST_F(TuningOutputTest, GenerateComparisonReport_CorrectDelta) {
  const auto params = makeTestParams();
  const auto report = TuningOutput::generateComparisonReport(params);

  // TEMPO: 34 -> 30, delta = -4
  EXPECT_TRUE(report.find("-4") != std::string::npos);
  // BLOCKED_PAWN_MID_WEIGHT: -2 -> 1, delta = +3
  EXPECT_TRUE(report.find("+3") != std::string::npos);
}

TEST_F(TuningOutputTest, GenerateComparisonReport_FlagsSignFlip) {
  const auto params = makeTestParams();
  const auto report = TuningOutput::generateComparisonReport(params);

  EXPECT_TRUE(report.find("SIGN-FLIP") != std::string::npos);
}

TEST_F(TuningOutputTest, GenerateComparisonReport_FlagsZeroedOut) {
  const auto params = makeTestParams();
  const auto report = TuningOutput::generateComparisonReport(params);

  EXPECT_TRUE(report.find("->ZERO") != std::string::npos);
}

TEST_F(TuningOutputTest, GenerateComparisonReport_FlagsUnchanged) {
  const auto params = makeTestParams();
  const auto report = TuningOutput::generateComparisonReport(params);

  EXPECT_TRUE(report.find("(unchanged)") != std::string::npos);
}

TEST_F(TuningOutputTest, WriteComparisonReport_CreatesFile) {
  const auto params = makeTestParams();
  const std::string path = "test_comparison.txt";

  TuningOutput::writeComparisonReport(path, params);
  ASSERT_TRUE(std::filesystem::exists(path));

  const auto content = readFile(path);
  EXPECT_TRUE(content.find("TEMPO") != std::string::npos);
  EXPECT_TRUE(content.find("SIGN-FLIP") != std::string::npos);

  std::filesystem::remove(path);
}

TEST_F(TuningOutputTest, WriteComparisonReport_BadPath) {
  const auto params = makeTestParams();
  EXPECT_THROW(TuningOutput::writeComparisonReport("/nonexistent/dir/file.txt", params), std::runtime_error);
}

// =========================================================================
// Registry round-trip: build params from real registry, generate YAML
// =========================================================================

TEST_F(TuningOutputTest, RegistryParams_YamlGeneration) {
  const auto& search = ConfigManager::instance().search();
  const auto& eval   = ConfigManager::instance().eval();
  auto params = TuningParameter::buildFromRegistry(search, eval);

  // Modify a few params to simulate tuning
  for (auto& p : params) {
    if (p.name == "TEMPO") {
      p.currentValue = 30;
    }
    if (p.name == "KING_SAFETY_TABLE[5]") {
      p.currentValue = 55;
    }
  }

  const auto yaml = TuningOutput::generateParamsYaml(params, 1.196);

  // Should contain coalesced KING_SAFETY_TABLE
  EXPECT_TRUE(yaml.find("KING_SAFETY_TABLE:") != std::string::npos);
  // Should not have individual element notation
  EXPECT_TRUE(yaml.find("KING_SAFETY_TABLE[") == std::string::npos);
  // Should contain TEMPO
  EXPECT_TRUE(yaml.find("TEMPO: 30") != std::string::npos);
}

TEST_F(TuningOutputTest, RegistryParams_ComparisonReport) {
  const auto& search = ConfigManager::instance().search();
  const auto& eval   = ConfigManager::instance().eval();
  auto params = TuningParameter::buildFromRegistry(search, eval);

  // Modify some params
  for (auto& p : params) {
    if (p.configName == "TEMPO") {
      p.currentValue = p.originalValue - 2;
    }
  }

  const auto report = TuningOutput::generateComparisonReport(params);

  EXPECT_TRUE(report.find("TEMPO") != std::string::npos);
  EXPECT_TRUE(report.find("Total parameters:") != std::string::npos);
  // Verify the correct total count matches buildFromRegistry
  const auto expectedCount = std::format("Total parameters:  {}", params.size());
  EXPECT_TRUE(report.find(expectedCount) != std::string::npos)
    << "Expected: " << expectedCount << "\nReport:\n" << report.substr(0, 500);
}

// =========================================================================
// Edge cases
// =========================================================================

TEST_F(TuningOutputTest, AllParamsUnchanged) {
  auto params = makeTestParams();
  // Reset all to original
  for (auto& p : params) {
    p.currentValue = p.originalValue;
  }

  const auto report = TuningOutput::generateComparisonReport(params);
  EXPECT_TRUE(report.find("Changed:           0") != std::string::npos);
  // No sign-flip or zeroed-out lines expected
  EXPECT_TRUE(report.find("Sign-flipped") == std::string::npos);
  EXPECT_TRUE(report.find("Zeroed out") == std::string::npos);
}

TEST_F(TuningOutputTest, ChangePercentage_Calculation) {
  std::vector<TuningParameter> params;
  TuningParameter p;
  p.name          = "TEST_PARAM";
  p.configName    = "TEST_PARAM";
  p.originalValue = 100;
  p.currentValue  = 120;
  p.arrayIndex    = -1;
  p.arraySize     = 0;
  params.push_back(p);

  const auto report = TuningOutput::generateComparisonReport(params);
  // Delta = +20, original = 100, change = +20.0%
  EXPECT_TRUE(report.find("+20.0%") != std::string::npos)
    << "Report:\n" << report;
}

TEST_F(TuningOutputTest, ChangePercentage_FromZero) {
  std::vector<TuningParameter> params;
  TuningParameter p;
  p.name          = "FROM_ZERO";
  p.configName    = "FROM_ZERO";
  p.originalValue = 0;
  p.currentValue  = 5;
  p.arrayIndex    = -1;
  p.arraySize     = 0;
  params.push_back(p);

  const auto report = TuningOutput::generateComparisonReport(params);
  // Original is 0, so percentage is "new" not a numeric value
  EXPECT_TRUE(report.find("new") != std::string::npos);
}

// =========================================================================
// Phase 6.10 — Additional edge case tests
// =========================================================================

TEST_F(TuningOutputTest, GenerateParamsYaml_SingleElementArray) {
  // An array with exactly 1 element should still be coalesced (just a single value)
  std::vector<TuningParameter> params;

  TuningParameter pa;
  pa.name          = "SINGLE_ARRAY[0]";
  pa.configName    = "SINGLE_ARRAY";
  pa.originalValue = 10;
  pa.currentValue  = 15;
  pa.arrayIndex    = 0;
  pa.arraySize     = 1;
  params.push_back(pa);

  const auto yaml = TuningOutput::generateParamsYaml(params);

  // Should coalesce to "SINGLE_ARRAY: 15" (single element)
  EXPECT_TRUE(yaml.find("SINGLE_ARRAY: 15") != std::string::npos)
    << "Single-element array should be coalesced. YAML:\n" << yaml;
  EXPECT_TRUE(yaml.find("SINGLE_ARRAY[0]") == std::string::npos)
    << "Array element notation should not appear";
}

TEST_F(TuningOutputTest, GenerateComparisonReport_AllParamsChanged) {
  auto params = makeTestParams();
  // Ensure every param is changed
  for (auto& p : params) {
    if (p.currentValue == p.originalValue) {
      p.currentValue = p.originalValue + 1;
    }
  }

  const auto report = TuningOutput::generateComparisonReport(params);
  EXPECT_TRUE(report.find("Unchanged:         0") != std::string::npos)
    << "All params changed → 0 unchanged. Report:\n" << report.substr(0, 500);
}

TEST_F(TuningOutputTest, GenerateComparisonReport_LargeNegativeDelta) {
  std::vector<TuningParameter> params;
  TuningParameter p;
  p.name          = "BIG_CHANGE";
  p.configName    = "BIG_CHANGE";
  p.originalValue = 500;
  p.currentValue  = -500;
  p.arrayIndex    = -1;
  p.arraySize     = 0;
  params.push_back(p);

  const auto report = TuningOutput::generateComparisonReport(params);
  EXPECT_TRUE(report.find("BIG_CHANGE") != std::string::npos);
  EXPECT_TRUE(report.find("-1000") != std::string::npos) << "Delta should be -1000";
  EXPECT_TRUE(report.find("SIGN-FLIP") != std::string::npos) << "Should flag sign flip";
}

TEST_F(TuningOutputTest, GenerateParamsYaml_MixedScalarsAndArrays) {
  // Verify ordering: scalars first, then arrays (or interleaved correctly)
  std::vector<TuningParameter> params;

  // Scalar
  TuningParameter s1;
  s1.name = "A_SCALAR"; s1.configName = "A_SCALAR";
  s1.currentValue = 10; s1.arrayIndex = -1; s1.arraySize = 0;
  params.push_back(s1);

  // Array (2 elements)
  for (int i = 0; i < 2; ++i) {
    TuningParameter a;
    a.name = "B_ARRAY[" + std::to_string(i) + "]"; a.configName = "B_ARRAY";
    a.currentValue = (i + 1) * 5; a.arrayIndex = i; a.arraySize = 2;
    params.push_back(a);
  }

  // Another scalar
  TuningParameter s2;
  s2.name = "C_SCALAR"; s2.configName = "C_SCALAR";
  s2.currentValue = 20; s2.arrayIndex = -1; s2.arraySize = 0;
  params.push_back(s2);

  const auto yaml = TuningOutput::generateParamsYaml(params);

  EXPECT_TRUE(yaml.find("A_SCALAR: 10") != std::string::npos);
  EXPECT_TRUE(yaml.find("B_ARRAY: 5,10") != std::string::npos);
  EXPECT_TRUE(yaml.find("C_SCALAR: 20") != std::string::npos);
}
