name: CMake

on:
  push:
    branches:
      #   - master
      #   - dev_v0.4
      - githubWorkflowTests

  pull_request:
#    branches:
#    - master

jobs:
  build:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    #    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu_Latest",
            os: ubuntu-latest,
            artifact: "FrankyCPP_v0.4_linux.zip",
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            archiver: "zip",
            generators: "Ninja"
          }
          - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            artifact: "FrankyCPP_v0.4_win.zip",
            build_type: "Release",
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat",
            archiver: "zip",
            generators: "Visual Studio 16 2019"
          }
          - {
            name: "macOS Latest Clang",
            os: macos-latest,
            artifact: "macos_clang.zip",
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            archiver: "zip",
            generators: "Ninja"
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

# ##############################################################################
# UBUNTU
# ##############################################################################

      - name: Install dependencies (ubuntu)
        if: startsWith(matrix.config.name, 'Ubuntu_Latest')
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake
          ninja --version
          cmake --version
          gcc --version

      - name: Cache Boost Build (ubuntu)
        if: startsWith(matrix.config.name, 'Ubuntu_Latest')
        id: cache-boost-build-ubuntu
        uses: actions/cache@v2.1.6
        with:
          path: boost_1_76_0
          key: ${{ runner.os }}-boost-build

      - name: Download and build BOOST (ubuntu)
        if: startsWith(matrix.config.name, 'Ubuntu_Latest') && steps.cache-boost-build-ubuntu.outputs.cache-hit != 'true'
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz >> /dev/null 2>&1
          tar xfz boost_1_76_0.tar.gz
          cd boost_1_76_0/
          ./bootstrap.sh --with-libraries=serialization,program_options
          ./b2
          cd ..

      - name: Install BOOST (ubuntu)
        if: startsWith(matrix.config.name, 'Ubuntu_Latest')
        run: |
          cd boost_1_76_0/
          sudo ./b2 install >> /dev/null 2>&1
          cd ..

# ##############################################################################
# WINDOWS
# ##############################################################################

      - name: Install dependencies (windows)
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install ninja cmake wget zip unzip --no-progress
          ninja --version
          cmake --version
          wget --version

      - name: Install BOOST (windows)
        if: startsWith(matrix.config.os, 'windows') && steps.cache-boost-build-windows.outputs.cache-hit != 'true'
        run: |
          choco install boost-msvc-14.2
#
#      - name: Cache Boost Install (windows)
#        if: startsWith(matrix.config.os, 'windows')
#        id: cache-boost-build-windows
#        uses: actions/cache@v2.1.6
#        with:
#          path: boost_1_76_0
#          key: ${{ runner.os }}-boost-build
#
#      - name: Download and build BOOST (windows)
#        if: startsWith(matrix.config.os, 'windows') && steps.cache-boost-build-windows.outputs.cache-hit != 'true'
#        run: |
#          wget -q https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.zip
#          unzip -q boost_1_76_0.zip
#          cd boost_1_76_0/
#          ./bootstrap.bat --with-libraries=serialization,program_options
#          ./b2
#          cd ..
#
#      - name: Install BOOST (windows)
#        if: startsWith(matrix.config.os, 'windows')
#        run: |
#          cd boost_1_76_0/
#          sudo ./b2 install >> /dev/null 2>&1
#          cd ..

# ##############################################################################
#  MACOS
# ##############################################################################

      - name: Install dependencies (macos)
        if: startsWith(matrix.config.os, 'macos')
        run: |
          brew install p7zip cmake ninja
          ninja --version
          cmake --version

      - name: Cache Boost Build (macos)
        if: startsWith(matrix.config.os, 'macos')
        id: cache-boost-build-macos
        uses: actions/cache@v2.1.6
        with:
          path: boost_1_76_0
          key: ${{ runner.os }}-boost-build

      - name: Download and build BOOST (macos)
        if: startsWith(matrix.config.os, 'macos') && steps.cache-boost-build-macos.outputs.cache-hit != 'true'
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz >> /dev/null 2>&1
          tar xfz boost_1_76_0.tar.gz
          cd boost_1_76_0/
          ./bootstrap.sh --with-libraries=serialization,program_options
          ./b2
          cd ..

      - name: Install BOOST (macos)
        if: startsWith(matrix.config.os, 'macos')
        run: |
          cd boost_1_76_0/
          sudo ./b2 install >> /dev/null 2>&1
          cd ..

# ##############################################################################
# ALL
# ##############################################################################

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -G "${{ matrix.config.generators }}"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config.build_type }} --parallel

      - name: Test
        if: startsWith(matrix.config.name, 'Ubuntu_Latest') || startsWith(matrix.config.name, 'macos')
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{ matrix.config.build_type }} -E "(SpeedTests|TimingTests)"

      - name: Run benchmark test
        if: startsWith(matrix.config.name, 'Ubuntu_Latest')
        working-directory: ${{github.workspace}}/build
        run: ./testbench/FrankyCPP_v0.4_Bench

      - name: Run PERFT test
        if: startsWith(matrix.config.name, 'Ubuntu_Latest')
        working-directory: ${{github.workspace}}/build
        run: ./src/FrankyCPP_v0.4 --perft --endDepth=5
