name: CMake Matrix Build

# This github workflow runs a build on all three platforms which are supported by FrankyCPP.
# Tests are only run on Linux for the time being as some how Windows and Mac tests fail due to
# unknown reasons. Most likely because of github platform specific reasons (folders, etc.).

on:
  push:
    branches:
      - master
      - dev_v0.4
      - githubWorkflowTests

  pull_request:
    branches:
      - master

jobs:
  build:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    #    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu_Latest_GNU",
            os: ubuntu-latest,
            artifact: "FrankyCPP_v0.4_linux.zip",
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            generators: "Ninja",
            archiver: "zip",
            executable: "./src/FrankyCPP_v0.4",
            test_exec: "./test/FrankyCPP_v0.4_Test",
            check: true,
            test: true,
            benchmark: true,
            perft: true
          }
          - {
            name: "Windows_Latest_MSVC",
            os: windows-latest,
            artifact: "FrankyCPP_v0.4_win.zip",
            build_type: "Release",
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat",
            generators: "Visual Studio 16 2019",
            archiver: "zip",
            executable: "./src/Release/FrankyCPP_v0.4.exe",
            test_exec: "./test/FrankyCPP_v0.4_Test.exe",
            check: true,
            test: false,
            benchmark: false,
            perft: true
          }
          - {
            name: "MacOS_Latest_Clang",
            os: macos-latest,
            artifact: "macos_clang.zip",
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            generators: "Ninja",
            archiver: "zip",
            executable: "./src/FrankyCPP_v0.4",
            test_exec: "./test/FrankyCPP_v0.4_Test",
            check: true,
            test: false,
            benchmark: false,
            perft: false
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

# ##############################################################################
# UBUNTU
# ##############################################################################

      - name: Install dependencies (ubuntu)
        if: startsWith(matrix.config.name, 'Ubuntu_Latest')
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake
          ninja --version
          cmake --version
          gcc --version

      - name: Cache Boost Build (ubuntu)
        if: startsWith(matrix.config.name, 'Ubuntu_Latest')
        id: cache-boost-build-ubuntu
        uses: actions/cache@v2.1.6
        with:
          path: boost_1_76_0
          key: ${{ runner.os }}-boost-build

      - name: Download and build BOOST (ubuntu)
        if: startsWith(matrix.config.name, 'Ubuntu_Latest') && steps.cache-boost-build-ubuntu.outputs.cache-hit != 'true'
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz >> /dev/null 2>&1
          tar xfz boost_1_76_0.tar.gz
          cd boost_1_76_0/
          ./bootstrap.sh --with-libraries=serialization,program_options
          ./b2
          cd ..

      - name: Install BOOST (ubuntu)
        if: startsWith(matrix.config.name, 'Ubuntu_Latest')
        run: |
          cd boost_1_76_0/
          sudo ./b2 install >> /dev/null 2>&1
          cd ..

# ##############################################################################
# WINDOWS
# ##############################################################################

      - name: Install dependencies (windows)
        if: startsWith(matrix.config.name, 'Windows')
        run: |
          choco install ninja cmake --no-progress
          ninja --version
          cmake --version

# wget zip unzip

      - name: Install BOOST (windows)
        if: startsWith(matrix.config.name, 'Windows') && steps.cache-boost-build-windows.outputs.cache-hit != 'true'
        run: |
          choco install boost-msvc-14.2 --no-progress


# ./b2 --with-program_options --with-filesystem --with-system

# ##############################################################################
#  MACOS
# ##############################################################################

      - name: Install dependencies (macos)
        if: startsWith(matrix.config.name, 'MacOs')
        run: |
          brew install p7zip cmake ninja
          ninja --version
          cmake --version

      - name: Cache Boost Build (macos)
        if: startsWith(matrix.config.name, 'MacOs')
        id: cache-boost-build-macos
        uses: actions/cache@v2.1.6
        with:
          path: boost_1_76_0
          key: ${{ runner.os }}-boost-build

      - name: Download and build BOOST (macos)
        if: startsWith(matrix.config.name, 'MacOs') && steps.cache-boost-build-macos.outputs.cache-hit != 'true'
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz >> /dev/null 2>&1
          tar xfz boost_1_76_0.tar.gz
          cd boost_1_76_0/
          ./bootstrap.sh --with-libraries=serialization,program_options
          ./b2
          cd ..

      - name: Install BOOST (macos)
        if: startsWith(matrix.config.name, 'MacOs')
        run: |
          cd boost_1_76_0/
          sudo ./b2 install >> /dev/null 2>&1
          cd ..

# ##############################################################################
# ALL
# ##############################################################################

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -G "${{ matrix.config.generators }}"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config.build_type }} --parallel

      - name: Check build
        if: matrix.config.check
        working-directory: ${{github.workspace}}/build
        run: |
          ${{ matrix.config.executable }} --version
          ls -la .
          ls -la ./src
          ls -la ./test
          ls -la ./testbench

# Below tests do not yet all run on Windows and Mac together with github workflows.
# They run fine on actual hardware. Needs more time investment to figure this out.

      - name: Test
        if: matrix.config.test
        working-directory: ${{github.workspace}}/build/test
        run: ${{ matrix.config.test_exec }} -*SpeedTests.*:-*TimingTests.*
        #run: ctest -C ${{ matrix.config.build_type }} -E "(SpeedTests|TimingTests)"

      - name: Run benchmark test
        if: matrix.config.benchmark
        working-directory: ${{github.workspace}}/build
        run: ./testbench/FrankyCPP_v0.4_Bench

      - name: Run PERFT test
        if: matrix.config.perft
        working-directory: ${{github.workspace}}/build
        run: ${{ matrix.config.executable }} -c ${{github.workspace}}/config/FrankyCPP.cfg --perft --endDepth=5
