name: Todo2Issue
on:
  push:
    branches:
      - master
      - dev_*
      - githubWorkflowTests
  pull_request:
    branches:
      - master
      - dev_*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run tdg-github-action
        uses: ribtoks/tdg-github-action@master
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}
          LABEL: "TODO"
          MIN_WORDS: 3
          MIN_CHARACTERS: 40
          ADD_LIMIT: 0
          CLOSE_LIMIT: 0
          ROOT: "src"
          PROJECT_COLUMN_ID: 9828767
          INCLUDE_PATTERN: "\\.(cpp|h)$"
